// Modular AI service layer. Every function here is SIMULATED for the prototype.
// Swap the bodies for computer-vision models, edge models, weather APIs, IoT sensors
// or external AI APIs without touching the UI — the return contracts stay the same.
import { EVENT_LABEL, fmtDate, summarize, type Lot, type LotEvent } from "./data";

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

export interface IntakeResult {
  grade: "A" | "B" | "C";
  estimatedQuality: string;
  detectedIssues: { label: string; level: "Low" | "Medium" | "High" }[];
  confidence: number;
  simulated: true;
}
export async function intakeGrader(_image: string | null): Promise<IntakeResult> {
  await wait(1800);
  return {
    grade: "A",
    estimatedQuality: "High",
    detectedIssues: [
      { label: "Defect risk", level: "Low" },
      { label: "Underripe cherries", level: "Low" },
      { label: "Damaged cherries", level: "Low" },
    ],
    confidence: 91,
    simulated: true,
  };
}

export type WaterClass = "CLEAN" | "WATCH" | "POTENTIAL HIGH RISK";
export interface WaterResult {
  classification: WaterClass;
  confidence: number;
  riskFlags: string[];
  swahili: string;
  simulated: true;
}
export async function waterAuditor(_image: string | null, demoOutcome: WaterClass = "CLEAN"): Promise<WaterResult> {
  await wait(2000);
  const map: Record<WaterClass, Omit<WaterResult, "classification" | "simulated">> = {
    CLEAN: { confidence: 94, riskFlags: [], swahili: "Maji yameainishwa kuwa safi." },
    WATCH: { confidence: 82, riskFlags: ["Slight turbidity", "Foam near outlet"], swahili: "Maji yanahitaji ufuatiliaji." },
    "POTENTIAL HIGH RISK": { confidence: 87, riskFlags: ["High turbidity", "Dark colouration", "Pulp residue"], swahili: "Maji yanaweza kuwa na hatari kubwa. Pima maabara." },
  };
  return { classification: demoOutcome, simulated: true, ...map[demoOutcome] };
}

export interface Weather { temperature: number; humidity: number; rainProbability: number; windKmh: number }
export interface DryingRisk { riskLevel: "LOW" | "MEDIUM" | "HIGH"; probability: number; prediction: string; recommendation: string; simulated: true }
export async function dryingRiskPredictor(weather: Weather, sensors: { moisture: number; days: number }, _lot: Lot): Promise<DryingRisk> {
  await wait(1200);
  const p = weather.rainProbability;
  if (p >= 60 || weather.humidity > 80)
    return { riskLevel: "HIGH", probability: p, prediction: "Rain likely within the next 60 minutes.", recommendation: "Move coffee to covered drying area.", simulated: true };
  if (p >= 30 || sensors.moisture > 16)
    return { riskLevel: "MEDIUM", probability: p, prediction: "Possible showers this afternoon.", recommendation: "Prepare covers and turn parchment hourly.", simulated: true };
  return { riskLevel: "LOW", probability: p, prediction: "Stable drying conditions.", recommendation: "Continue normal drying.", simulated: true };
}

export interface AssistantAnswer { answer: string; facts: string[]; aiNotes: string[]; supportingEvents: string[] }

// Rule-based reasoning over structured lot events. Replace with an LLM call that
// receives the same event list as context.
export async function lotAssistant(lot: Lot, farmerName: string, events: LotEvent[], question: string): Promise<AssistantAnswer> {
  await wait(900);
  const q = question.toLowerCase();
  const s = summarize(lot, events);
  const by = (t: LotEvent["type"]) => s.events.filter((e) => e.type === t);
  const harvest = by("HARVEST")[0];
  const intake = by("INTAKE").at(-1);
  const water = by("WATER_AUDIT").at(-1);
  const alerts = by("WEATHER_ALERT");
  const interventions = by("DRYING_INTERVENTION");
  const dry = by("DRYING_START")[0];
  const moist = by("MOISTURE_CHECK").at(-1);
  const ids = (...e: (LotEvent | undefined)[]) => e.filter(Boolean).map((x) => x!.id);

  if (q.includes("where") || q.includes("origin") || q.includes("come from")) {
    return {
      answer: `${lot.id} comes from ${farmerName}'s farm in ${lot.origin}${harvest ? ` (${harvest.location})` : ""}. The harvest was recorded on ${harvest ? fmtDate(harvest.timestamp) : "—"}${harvest?.gps ? ` with GPS ${harvest.gps}` : ""}.`,
      facts: harvest ? [`Harvest event VERIFIED · ${harvest.device}`] : [],
      aiNotes: [],
      supportingEvents: ids(harvest),
    };
  }
  if (q.includes("dry")) {
    return {
      answer: dry
        ? `Drying started on ${fmtDate(dry.timestamp)} on bed ${dry.data?.bed}. ${alerts.length} rain-risk alert(s) were generated by the AI Drying Guard${interventions.length ? `, and the operator recorded: "${interventions[0]!.data?.action ?? interventions[0]!.notes}".` : "."}${moist ? ` Final moisture was ${moist.data?.moisture}%.` : ""}`
        : "No drying start has been recorded yet for this lot.",
      facts: [...interventions.map(() => "Intervention recorded by Station Manager (VERIFIED)"), ...(moist ? [`Moisture ${moist.data?.moisture}% recorded`] : [])],
      aiNotes: alerts.map((a) => `AI prediction: ${a.aiAssessment} (${a.aiConfidence}% probability)`),
      supportingEvents: ids(dry, ...alerts, ...interventions, moist),
    };
  }
  if (q.includes("water")) {
    return {
      answer: water
        ? `Yes. A water audit was recorded on ${fmtDate(water.timestamp, true)} by ${water.operator}. The AI visual screening classified the effluent as ${water.data?.result} with ${water.aiConfidence}% confidence. This is a screening, not a laboratory test — lab confirmation may be required.`
        : "No water audit has been recorded for this lot yet. This is MISSING evidence.",
      facts: water ? [`Photo, GPS and timestamp recorded`] : [],
      aiNotes: water ? [`AI visual screening: ${water.data?.result} (${water.aiConfidence}%)`] : [],
      supportingEvents: ids(water),
    };
  }
  if (q.includes("grade") || q.includes("evidence")) {
    return {
      answer: intake
        ? `The Grade ${intake.data?.grade} result is supported by: a cherry sample photo taken at intake, an AI grade recommendation (${intake.aiConfidence}% confidence), and a human confirmation by ${intake.operator}. ${intake.data?.receivedKg} kg was weighed on ${intake.device}.`
        : "There is no intake grading record yet.",
      facts: intake ? [`Weight ${intake.data?.receivedKg} kg (scale)`, `Operator confirmation: ${intake.humanConfirmation}`] : [],
      aiNotes: intake ? [`AI recommendation: ${intake.aiAssessment}`] : [],
      supportingEvents: ids(intake),
    };
  }
  if (q.includes("missing")) {
    const missing = ["HARVEST", "INTAKE", "WATER_AUDIT", "DRYING_START", "MOISTURE_CHECK", "STORAGE", "SALE"].filter(
      (t) => !s.events.some((e) => e.type === t && e.status !== "PENDING"),
    );
    return {
      answer: missing.length
        ? `Records not yet complete: ${missing.map((t) => EVENT_LABEL[t as LotEvent["type"]]).join(", ")}. Traceability completeness is ${s.completeness}%.`
        : `No required records are missing. Completeness is ${s.completeness}%.`,
      facts: [],
      aiNotes: [],
      supportingEvents: s.events.filter((e) => e.status === "PENDING").map((e) => e.id),
    };
  }
  // default: summary
  return {
    answer: `${farmerName}'s lot ${lot.id} was harvested on ${harvest ? fmtDate(harvest.timestamp) : "—"}${intake ? ` and received at the washing station on ${fmtDate(intake.timestamp)} (${intake.data?.receivedKg} kg). The lot received an AI Grade ${intake.data?.grade} recommendation that was ${intake.humanConfirmation === "CONFIRMED" ? "confirmed by the station operator" : "not yet confirmed"}` : ""}.${water ? ` A water screening was recorded as ${water.data?.result} with ${water.aiConfidence}% AI confidence.` : ""}${alerts.length ? ` During drying, ${alerts.length} high-rain-risk alert was generated${interventions.length ? " and the coffee was moved under cover" : ""}.` : ""}${moist ? ` Final recorded moisture was ${moist.data?.moisture}%.` : ""} The lot currently has ${s.completeness}% traceability completeness.`,
    facts: [harvest && "Harvest location (VERIFIED)", intake && `Weight ${intake.data?.receivedKg} kg + operator confirmation`, interventions[0] && "Rain intervention (VERIFIED)", moist && `Moisture ${moist.data?.moisture}%`].filter(Boolean) as string[],
    aiNotes: [intake && `Grade recommendation (${intake.aiConfidence}%)`, water && `Water screening (${water.aiConfidence}%)`, alerts[0] && "Rain-risk prediction"].filter(Boolean) as string[],
    supportingEvents: s.events.map((e) => e.id),
  };
}
