/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DryingRouteImport } from './routes/drying'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MoistureRouteImport } from './routes/moisture'
import { Route as MoveRouteImport } from './routes/move'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WaterRouteImport } from './routes/water'
import { Route as BedsIndexRouteImport } from './routes/beds.index'
import { Route as BedsBedIdRouteImport } from './routes/beds.$bedId'
import { Route as BuyerLotIdRouteImport } from './routes/buyer.$lotId'
import { Route as JourneyIndexRouteImport } from './routes/journey.index'
import { Route as JourneyLotIdRouteImport } from './routes/journey.$lotId'
import { Route as LotsLotIdRouteImport } from './routes/lots.$lotId'
import { Route as ReceiptLotIdRouteImport } from './routes/receipt.$lotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DryingRoute = DryingRouteImport.update({
  id: '/drying',
  path: '/drying',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MoistureRoute = MoistureRouteImport.update({
  id: '/moisture',
  path: '/moisture',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveRoute = MoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsIndexRoute = BedsIndexRouteImport.update({
  id: '/beds/',
  path: '/beds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsBedIdRoute = BedsBedIdRouteImport.update({
  id: '/beds/$bedId',
  path: '/beds/$bedId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerLotIdRoute = BuyerLotIdRouteImport.update({
  id: '/buyer/$lotId',
  path: '/buyer/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIndexRoute = JourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyLotIdRoute = JourneyLotIdRouteImport.update({
  id: '/$lotId',
  path: '/$lotId',
  getParentRoute: () => JourneyRoute,
} as any)
const LotsLotIdRoute = LotsLotIdRouteImport.update({
  id: '/lots/$lotId',
  path: '/lots/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptLotIdRoute = ReceiptLotIdRouteImport.update({
  id: '/receipt/$lotId',
  path: '/receipt/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/drying': typeof DryingRoute
  '/intake': typeof IntakeRoute
  '/journey': typeof JourneyRouteWithChildren
  '/moisture': typeof MoistureRoute
  '/move': typeof MoveRoute
  '/quality': typeof QualityRoute
  '/tools': typeof ToolsRoute
  '/water': typeof WaterRoute
  '/beds/$bedId': typeof BedsBedIdRoute
  '/buyer/$lotId': typeof BuyerLotIdRoute
  '/journey/$lotId': typeof JourneyLotIdRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/receipt/$lotId': typeof ReceiptLotIdRoute
  '/beds/': typeof BedsIndexRoute
  '/journey/': typeof JourneyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/drying': typeof DryingRoute
  '/intake': typeof IntakeRoute
  '/moisture': typeof MoistureRoute
  '/move': typeof MoveRoute
  '/quality': typeof QualityRoute
  '/tools': typeof ToolsRoute
  '/water': typeof WaterRoute
  '/beds/$bedId': typeof BedsBedIdRoute
  '/buyer/$lotId': typeof BuyerLotIdRoute
  '/journey/$lotId': typeof JourneyLotIdRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/receipt/$lotId': typeof ReceiptLotIdRoute
  '/beds': typeof BedsIndexRoute
  '/journey': typeof JourneyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/drying': typeof DryingRoute
  '/intake': typeof IntakeRoute
  '/journey': typeof JourneyRouteWithChildren
  '/moisture': typeof MoistureRoute
  '/move': typeof MoveRoute
  '/quality': typeof QualityRoute
  '/tools': typeof ToolsRoute
  '/water': typeof WaterRoute
  '/beds/$bedId': typeof BedsBedIdRoute
  '/buyer/$lotId': typeof BuyerLotIdRoute
  '/journey/$lotId': typeof JourneyLotIdRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/receipt/$lotId': typeof ReceiptLotIdRoute
  '/beds/': typeof BedsIndexRoute
  '/journey/': typeof JourneyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/drying'
    | '/intake'
    | '/journey'
    | '/moisture'
    | '/move'
    | '/quality'
    | '/tools'
    | '/water'
    | '/beds/$bedId'
    | '/buyer/$lotId'
    | '/journey/$lotId'
    | '/lots/$lotId'
    | '/receipt/$lotId'
    | '/beds/'
    | '/journey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/drying'
    | '/intake'
    | '/moisture'
    | '/move'
    | '/quality'
    | '/tools'
    | '/water'
    | '/beds/$bedId'
    | '/buyer/$lotId'
    | '/journey/$lotId'
    | '/lots/$lotId'
    | '/receipt/$lotId'
    | '/beds'
    | '/journey'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/assistant'
    | '/drying'
    | '/intake'
    | '/journey'
    | '/moisture'
    | '/move'
    | '/quality'
    | '/tools'
    | '/water'
    | '/beds/$bedId'
    | '/buyer/$lotId'
    | '/journey/$lotId'
    | '/lots/$lotId'
    | '/receipt/$lotId'
    | '/beds/'
    | '/journey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AssistantRoute: typeof AssistantRoute
  DryingRoute: typeof DryingRoute
  IntakeRoute: typeof IntakeRoute
  JourneyRoute: typeof JourneyRouteWithChildren
  MoistureRoute: typeof MoistureRoute
  MoveRoute: typeof MoveRoute
  QualityRoute: typeof QualityRoute
  ToolsRoute: typeof ToolsRoute
  WaterRoute: typeof WaterRoute
  BedsBedIdRoute: typeof BedsBedIdRoute
  BuyerLotIdRoute: typeof BuyerLotIdRoute
  LotsLotIdRoute: typeof LotsLotIdRoute
  ReceiptLotIdRoute: typeof ReceiptLotIdRoute
  BedsIndexRoute: typeof BedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drying': {
      id: '/drying'
      path: '/drying'
      fullPath: '/drying'
      preLoaderRoute: typeof DryingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moisture': {
      id: '/moisture'
      path: '/moisture'
      fullPath: '/moisture'
      preLoaderRoute: typeof MoistureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move': {
      id: '/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof MoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beds/': {
      id: '/beds/'
      path: '/beds'
      fullPath: '/beds/'
      preLoaderRoute: typeof BedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beds/$bedId': {
      id: '/beds/$bedId'
      path: '/beds/$bedId'
      fullPath: '/beds/$bedId'
      preLoaderRoute: typeof BedsBedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/$lotId': {
      id: '/buyer/$lotId'
      path: '/buyer/$lotId'
      fullPath: '/buyer/$lotId'
      preLoaderRoute: typeof BuyerLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/': {
      id: '/journey/'
      path: '/'
      fullPath: '/journey/'
      preLoaderRoute: typeof JourneyIndexRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/$lotId': {
      id: '/journey/$lotId'
      path: '/$lotId'
      fullPath: '/journey/$lotId'
      preLoaderRoute: typeof JourneyLotIdRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/lots/$lotId': {
      id: '/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/lots/$lotId'
      preLoaderRoute: typeof LotsLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$lotId': {
      id: '/receipt/$lotId'
      path: '/receipt/$lotId'
      fullPath: '/receipt/$lotId'
      preLoaderRoute: typeof ReceiptLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JourneyRouteChildren {
  JourneyLotIdRoute: typeof JourneyLotIdRoute
  JourneyIndexRoute: typeof JourneyIndexRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyLotIdRoute: JourneyLotIdRoute,
  JourneyIndexRoute: JourneyIndexRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AssistantRoute: AssistantRoute,
  DryingRoute: DryingRoute,
  IntakeRoute: IntakeRoute,
  JourneyRoute: JourneyRouteWithChildren,
  MoistureRoute: MoistureRoute,
  MoveRoute: MoveRoute,
  QualityRoute: QualityRoute,
  ToolsRoute: ToolsRoute,
  WaterRoute: WaterRoute,
  BedsBedIdRoute: BedsBedIdRoute,
  BuyerLotIdRoute: BuyerLotIdRoute,
  LotsLotIdRoute: LotsLotIdRoute,
  ReceiptLotIdRoute: ReceiptLotIdRoute,
  BedsIndexRoute: BedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
